name: Joanna Patyk Website Pipeline
run-name: ${{ github.actor }} is testing on [${{ github.ref_name }}] 🚀
on: [push]

jobs:
    app-ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout branch [${{ github.ref_name }}]
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'
                  cache-dependency-path: '**/package-lock.json'

            - name: Install dependencies
              run: npm ci

            - name: Run Gulp
              run: npm run gulp-styles

            - name: Run ESLint
              run: npm run eslint-check

            - name: Run Prettier
              run: npm run prettier-check

            - name: Run Build
              run: npm run build
